# Generated by Django 2.2.4 on 2021-08-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnaBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='select',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='complite',
            field=models.BooleanField(default=False),
        ),
    ]
