# Generated by Django 2.2.4 on 2021-08-19 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qnaBoard', '0002_auto_20210819_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='complite',
            new_name='complete',
        ),
    ]
