# Generated by Django 2.2.4 on 2021-08-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boormiBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boormipost',
            old_name='complite',
            new_name='complete',
        ),
    ]
